# Generated by Django 3.1.6 on 2021-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mustard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('desc', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
