# Generated by Django 3.1.6 on 2021-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustard',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
