# Generated by Django 3.1.6 on 2021-02-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0002_mustard_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(default='Not Available', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('containerType', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, default='Not Available', max_length=200)),
                ('desc', models.CharField(blank=True, default='No Descriptions', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(default='Not Available', max_length=10)),
                ('photo', models.ImageField(upload_to='emp_photo/%Y/%m/%d/')),
                ('identity', models.FileField(upload_to='emp_identity/%Y/%m/%d/')),
                ('address', models.CharField(blank=True, default='Not Available', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MustardCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Name Not Available', max_length=100)),
                ('mobile', models.CharField(default='Not Available', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name Not Available', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(default='Not Available', max_length=10)),
                ('containerType', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('desc', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('expenseType', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mustard',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mustard',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='mustard',
            name='mobile',
            field=models.CharField(default='Not Available', max_length=10),
        ),
        migrations.AlterField(
            model_name='mustard',
            name='name',
            field=models.CharField(default='Name Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='mustard',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='EmpPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millapi.employee')),
            ],
        ),
    ]
