# Generated by Django 3.1.6 on 2021-02-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0004_remove_emppayment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empPayment',
            field=models.ForeignKey(default=4000, on_delete=django.db.models.deletion.CASCADE, to='millapi.emppayment'),
            preserve_default=False,
        ),
    ]
