# Generated by Django 3.1.6 on 2021-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0006_auto_20210213_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustardcake',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
