# Generated by Django 3.1.7 on 2021-03-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0007_auto_20210213_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duesType', models.CharField(max_length=50)),
                ('mobile', models.CharField(default='Not Available', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('isClear', models.BooleanField(default=False)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millapi.employee')),
            ],
        ),
    ]
