# Generated by Django 3.1.7 on 2021-03-03 16:21

from django.db import migrations, models
import millapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('millapi', '0008_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='duesFor',
            field=models.CharField(default='mustard', max_length=20, validators=[millapi.models.only_int]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dues',
            name='name',
            field=models.CharField(default='Name Not Available', max_length=100),
        ),
    ]
